### ISSUE TITLE
Gather ingredients

### ISSUE THREAD

**Issue by myka-p** [darbecker12/Pizza-Party#2]
## Ingredients needed:

for toppings:
- pizza sauce
- ham
- mozzarella cheese 
- pineapple chunks

for crust:
- yeast
- water
- oil 
- flour
- salt 
- sugar

## Definition of done:

All ingredients are measured and are ready to be mixed or added.

**Comment by EbrahimLadhi** [comment]
Measure the ingredients before adding to product.

**Comment by Warjumper** [comment]
Let's hit the store and grab some goods!

**Comment by eliewa** [comment]
Purchased ingredients and prepped items.

**Comment by EbrahimLadhi** [comment]
Make a budget list.

**Comment by eliewa** [comment]
Items have been prepped and ready to go!
