### ISSUE TITLE
Pre-Heat the oven

### ISSUE THREAD

**Issue by darbecker12** [darbecker12/Pizza-Party#3]
## Context
Searching in the recipe to find the ideal oven temperature

## Definition of Done
The oven is pre-heating to the desired temperature

**Comment by Warjumper** [comment]
What temp!?

**Comment by darbecker12** [comment]
@Warjumper Forgot to add that we are pre-heating to 450 F

**Comment by eliewa** [comment]
Ebrahim can you please preheat the oven?

**Comment by eliewa** [comment]
Oven has been preheated.

**Comment by Warjumper** [comment]
@eliewa Thank you!
